name: test suite

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: self-hosted
    container: ubuntu:noble
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: gallery3
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4']
    env:
      DB_DATABASE: gallery3
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
      DB_HOST: 127.0.0.1
    steps:
      - name: Install OS packages
        run: apt-get install -y imagemagick graphicsmagick dcraw ffmpeg git mysql-client

      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up MySQL
        run: |
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }}_test;' -h ${{ env.DB_HOST }} --port ${{ env.DB_PORT }} -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, gd, mysql, xml
          ini-values: post_max_size=256M, max_execution_time=180
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: |
          mkdir -p .cache
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            ~/.cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3

      - name: linter
        run: bin/linter.sh

      - name: phpcs
        run: bin/phpcs.sh

      - name: install db
        run: php ./installer/index.php
        env:
          MYSQL_HOST: ${{ env.DB_HOST }}:${{ env.DB_PORT }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}

      - name: tests
        run: php index.php test
